### ISSUE TITLE
Font på Post-it lapparna får gärna vara samma som på resterande text

### ISSUE THREAD

**Issue by BardNilz** [Dsek-LTH/dsek-nolla#17]
Titel says it all

**Comment by oliverlevay** [comment]
Okej, följde figman som har en annan font, är vi säkra på att vi vill ha samma font överallt ?

**Comment by BardNilz** [comment]
Ingen aning. Såg att den var faktiskt i olika font på Figman. Så kanske inte behövs ändån.
