### ISSUE TITLE
Bör sidan va "copyrightad" av D-Sektionen? 

### ISSUE THREAD

**Issue by BardNilz** [Dsek-LTH/dsek-nolla#20]
Exempel från K-sektionens nollningssida. 
![image](https://user-images.githubusercontent.com/80070896/177860087-b1e402c0-6953-451f-8335-a32771eff3c3.png)

**Comment by oliverlevay** [comment]
Jag kan fixa det om vi vill, men inget som jag tycker behövs.

**Comment by BardNilz** [comment]
Okey, då kanske de går o strunta i!
